/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/GuArU1OfdHp
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"

export function Accounts() {
  return (
    (<div className="flex flex-col min-h-screen">
      <main className="container mx-auto px-4 py-12 md:px-6 lg:py-16">
        <h1 className="text-3xl font-bold mb-8 text-center">Connect Your Accounts</h1>
        <div
          className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
          <Card
            className="bg-card text-card-foreground p-6 flex flex-col items-center justify-between">
            <div className="flex items-center gap-4">
              <TwitterIcon className="w-8 h-8 text-[#1DA1F2]" />
              <div>
                <h3 className="text-lg font-semibold">@twitterdev</h3>
                <p className="text-muted-foreground text-sm">Twitter</p>
              </div>
            </div>
            <Button variant="secondary">Connect</Button>
          </Card>
          <Card
            className="bg-card text-card-foreground p-6 flex flex-col items-center justify-between">
            <div className="flex items-center gap-4">
              <FacebookIcon className="w-8 h-8 text-[#1877F2]" />
              <div>
                <h3 className="text-lg font-semibold">Facebook</h3>
                <p className="text-muted-foreground text-sm">Facebook</p>
              </div>
            </div>
            <Button variant="secondary">Connect</Button>
          </Card>
          <Card
            className="bg-card text-card-foreground p-6 flex flex-col items-center justify-between">
            <div className="flex items-center gap-4">
              <InstagramIcon className="w-8 h-8 text-[#E1306C]" />
              <div>
                <h3 className="text-lg font-semibold">@instagram</h3>
                <p className="text-muted-foreground text-sm">Instagram</p>
              </div>
            </div>
            <Button variant="secondary">Connect</Button>
          </Card>
          <Card
            className="bg-card text-card-foreground p-6 flex flex-col items-center justify-between">
            <div className="flex items-center gap-4">
              <LinkedinIcon className="w-8 h-8 text-[#0077B5]" />
              <div>
                <h3 className="text-lg font-semibold">LinkedIn</h3>
                <p className="text-muted-foreground text-sm">LinkedIn</p>
              </div>
            </div>
            <Button variant="secondary">Connect</Button>
          </Card>
          <Card
            className="bg-card text-card-foreground p-6 flex flex-col items-center justify-between">
            <div className="flex items-center gap-4">
              <GitlabIcon className="w-8 h-8 text-[#333]" />
              <div>
                <h3 className="text-lg font-semibold">@github</h3>
                <p className="text-muted-foreground text-sm">GitHub</p>
              </div>
            </div>
            <Button variant="secondary">Connect</Button>
          </Card>
          <Card
            className="bg-card text-card-foreground p-6 flex flex-col items-center justify-between">
            <div className="flex items-center gap-4">
              <DiscIcon className="w-8 h-8 text-[#5865F2]" />
              <div>
                <h3 className="text-lg font-semibold">Discord</h3>
                <p className="text-muted-foreground text-sm">Discord</p>
              </div>
            </div>
            <Button variant="secondary">Connect</Button>
          </Card>
          <Card
            className="bg-card text-card-foreground p-6 flex flex-col items-center justify-between">
            <div className="flex items-center gap-4">
              <TwitchIcon className="w-8 h-8 text-[#9146FF]" />
              <div>
                <h3 className="text-lg font-semibold">@twitchdev</h3>
                <p className="text-muted-foreground text-sm">Twitch</p>
              </div>
            </div>
            <Button variant="secondary">Connect</Button>
          </Card>
          <Card
            className="bg-card text-card-foreground p-6 flex flex-col items-center justify-between">
            <div className="flex items-center gap-4">
              <YoutubeIcon className="w-8 h-8 text-[#FF0000]" />
              <div>
                <h3 className="text-lg font-semibold">YouTube</h3>
                <p className="text-muted-foreground text-sm">YouTube</p>
              </div>
            </div>
            <Button variant="secondary">Connect</Button>
          </Card>
        </div>
      </main>
      <footer className="bg-muted text-muted-foreground py-8">
        <div className="container mx-auto px-4 md:px-6">
          <h2 className="text-2xl font-bold mb-6">Transaction History</h2>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>User</TableHead>
                <TableHead>Social Media</TableHead>
                <TableHead>Amount</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell>
                  <div className="font-medium">John Doe</div>
                  <div className="text-muted-foreground text-sm">@johndoe</div>
                </TableCell>
                <TableCell>
                  <div className="flex items-center gap-2">
                    <TwitterIcon className="w-5 h-5 text-[#1DA1F2]" />
                    <span>Twitter</span>
                  </div>
                </TableCell>
                <TableCell className="text-right">$50.00</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>
                  <div className="font-medium">Jane Smith</div>
                  <div className="text-muted-foreground text-sm">@janesmith</div>
                </TableCell>
                <TableCell>
                  <div className="flex items-center gap-2">
                    <FacebookIcon className="w-5 h-5 text-[#1877F2]" />
                    <span>Facebook</span>
                  </div>
                </TableCell>
                <TableCell className="text-right">$75.00</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>
                  <div className="font-medium">Michael Johnson</div>
                  <div className="text-muted-foreground text-sm">@mjohnson</div>
                </TableCell>
                <TableCell>
                  <div className="flex items-center gap-2">
                    <InstagramIcon className="w-5 h-5 text-[#E1306C]" />
                    <span>Instagram</span>
                  </div>
                </TableCell>
                <TableCell className="text-right">$100.00</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>
                  <div className="font-medium">Emily Davis</div>
                  <div className="text-muted-foreground text-sm">@emilydavis</div>
                </TableCell>
                <TableCell>
                  <div className="flex items-center gap-2">
                    <LinkedinIcon className="w-5 h-5 text-[#0077B5]" />
                    <span>LinkedIn</span>
                  </div>
                </TableCell>
                <TableCell className="text-right">$125.00</TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>
      </footer>
    </div>)
  );
}

function DiscIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="2" />
    </svg>)
  );
}


function FacebookIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>)
  );
}


function GitlabIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="m22 13.29-3.33-10a.42.42 0 0 0-.14-.18.38.38 0 0 0-.22-.11.39.39 0 0 0-.23.07.42.42 0 0 0-.14.18l-2.26 6.67H8.32L6.1 3.26a.42.42 0 0 0-.1-.18.38.38 0 0 0-.26-.08.39.39 0 0 0-.23.07.42.42 0 0 0-.14.18L2 13.29a.74.74 0 0 0 .27.83L12 21l9.69-6.88a.71.71 0 0 0 .31-.83Z" />
    </svg>)
  );
}


function InstagramIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>)
  );
}


function LinkedinIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>)
  );
}


function TwitchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M21 2H3v16h5v4l4-4h5l4-4V2zm-10 9V7m5 4V7" />
    </svg>)
  );
}


function TwitterIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}


function YoutubeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17" />
      <path d="m10 15 5-3-5-3z" />
    </svg>)
  );
}
